version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  db_test:
    image: postgres
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: password
    expose:
      - 5433
    ports:
     - 5433:5432

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--","./main"]

