version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

#  app:
#    build: ./
#    ports:
#      - 8080:8080
